<img src="Numpy.jpg">

<src img = numpy.jpg >

**Documentation:** 
https://numpy.org/doc/1.13/contents.html

# Numpy
NumPy is a Python package. It stands for 'Numerical Python'. 
It is a library consisting of multidimensional array objects and a collection of routines for processing of array.
There are many contributors to this open source project.


# Numpy vs List
#### Python List:

1. Able to store different data types in the same list.
2. Storing each item in random location in the memory.
3. Good for the scenario where list can grow dynamically.
4. Inbuilt data type.
5. It has more inbuilt functions.
6. Appending will take less time in O(1) time.

#### NumPy Array:

1. Can store only one data type in an array at any time.
2. Storing each item is sequential which makes array more effective in processing.
3. Good for the scenario where the items are fixed size and same data time.
4. Need to install external library NumPy
5. No extra functions, so it will not more memory store.
6. Appending elements will take more time in O(N) time.


<img src="1D,2D,3D Array.png">

In [87]:
#To install numpy in jupyter notebook
!pip install numpy

In [88]:
#import numpy module with alias as np
import numpy as np 

In [89]:
#Define a numpy array passing a list with 1,2, and 3 as elements in it
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [90]:
# more than one dimensions 
import numpy as np 

In [91]:
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


# Dimensions in Arrays
Numpy array can be of n dimensions

Lets create arrays if different dimensions.

a=A numpy array with oone single integer 10

b=A numpy array passing a list having a list=[1, 2, 3]

c=A numpy array passing nested list having [[1, 2, 3],[4, 5, 6]] as elements.

d=A numpy array passing nested list having [[[1, 2, 3],[4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements.

In [92]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

Are you ready to check its dimension? Use ndim attribute on each varaible to check its dimension

In [93]:
#print dimensions of a,b,c and d
print('a dimensions:', a.ndim)
print('b dimensions:', b.ndim)
print('c dimensions:', c.ndim)
print('d dimensions:', d.ndim)

a dimensions: 0
b dimensions: 1
c dimensions: 2
d dimensions: 3


Lets print there shape as well.You can check shape using shape attribute

In [94]:
#print shape of each a,b,c and d
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


Lets check data type passed in our array.To check data type you can use dtype attributes

In [95]:
#print data type of c and d
print(c.dtype)
print(d.dtype)

int32
int32


Lets check the type of our variable.To check type of any numpy variable use type() fucntion

In [96]:
#print type of a and b variable
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [97]:
#lets check length of arrayb, using len() function
len(b)

3

In [98]:
#Define L1,L2,L3 and L4 as stated above
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)
print(l3)
print(l4)
print(type(l3))

[10 20 30]
[40 50 60]
<class 'numpy.ndarray'>


# Creating Numpy array

There are multiple ways to create numpy array.Lets walk over them

1. Using **arange()** function


In [99]:
#create a numpy array using arange with 1 and 11 paramter in it
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
#create an array using arange passing 1,11 and 2 as parameters
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [101]:
#create an numpy array using arange with 1 and 11 as paramter in it
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Using **eye()** Function

In [102]:
#create numpy array using eye function with 3 as passed paramter
np.eye(10, dtype = float)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Wohoo! eye return a 2-D array with ones on the diagonal and zeros elsewhere.

3. Using **zero()** function

In [103]:
#create a numpy array using zero function with (3, 2) as passed paramter takes 
np.zeros((3, 2), dtype=int) #default float

array([[0, 0],
       [0, 0],
       [0, 0]])

Zero function returns a new array of given shape and type, filled with zeros.

4. Using **Ones()** Function

In [104]:
#create a numpy array using ones function with (3, 2) as passed paramter takes
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

You noticed! ones function returns a new array of given shape and type, filled with ones.

5. Using **full()** Function

In [105]:
#create a numpy array using full function with (3, 2) and 2 as passed paramter takes
np.full((3, 2), 12)

array([[12, 12],
       [12, 12],
       [12, 12]])

<img src="np_eye_full.jpg">


6. Using **diag()** function

In [106]:
#create a numpy array using diag function  passing a list [1,2,3,4,5]
x = [1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

<img src="linspace.png">



In [107]:
#create an array with 100 values between 1 and 50 using linspace
np.linspace(1, 10, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# Numpy Random numbers

In [108]:
#Generate one random number between 0 and 1 using numpy's random.rand() fucntion.
np.random.random(1)[0]

0.2524734952094063

In [109]:
#so let say I want a random value between 0 and 50
np.random.randint(0, 50)

8

In [110]:
#get an array as stated above
np.random.randn(3, 3)

array([[-0.02886965,  1.2663579 ,  0.46218288],
       [ 0.28913201, -0.659586  , -0.10952909],
       [-0.12843797,  0.15525513, -1.16974748]])

# Numpy Reshape
Reshaping means changing the shape of an array.The shape of an array is the number of elements in each dimension. By reshaping we can add dimesions or change number of elements in each dimension.

<img src="reshape.png">

In [111]:
#Using arange() to generate numpy array x numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)


In [112]:
# Reshape x with 2 rows and 8 columns
n = x.reshape((4, 4))
print(n.shape)


(4, 4)


In [113]:
# convert to old dimesion
v = n.ravel()
print(v.shape)




(16,)


<img src="ravel.png">

In [114]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x.reshape((2,8), order="F")

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

<img src="flatten.png">

# NumPy Array Indexing

Array indexing is the same as accessing an array element. you can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [115]:
#flattening  x convert array into one dimension
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [116]:
#create an array a with all even numbers between 1 and 17
a = np.arange(2, 17, 2)
 
#print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [117]:
#Get third element in array a
a[2]

6

In [118]:
#print 3rd, 5th, and 7th element in array a
a[0:7:2]

array([ 2,  6, 10, 14])

Lets check the same for 2D array


In [119]:
#Define an array 2-D a with[[1,2,3],[4,5,6],[7,8,9]] as its elements
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
#print the 3rd element from the 3rd row of a 
a[2, 2]

9

<img src="index.png">

In [121]:
#Define an array b again with [[[1,2,3],[4,5,6],[7,8,9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9], [10, 11, 12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [122]:
#print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.
b[0][1][2]

6

have you heared about **negative indexing?**

We can use negative indexing to access an array from the end

In [ ]:
#print the second last element from the 2nd dim using negative indexing
b[-2][-1][-2]

Great job! So now you have learned how to indexing on various dimentions of numpy array.

# NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

1. We pass slice insted of index like this: [start:end]
2. We can also define the step, like this:[start:end:step].
3. If we don't pass start its considered 0
4. If we don't pass end its considered of array in that dimension
5. If we don't pass step its considered 1


#### 1. Array slicing in 1-D array

In [123]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
#Slice elements from 1st to 5th element from array arr:
arr[0:5]

array([1, 2, 3, 4, 5])

In [125]:
#Slice elements from index 5 to the end of the array arr: 
arr[5:]

array([ 6,  7,  8,  9, 10])

In [126]:
#Slice elements from beginning to index 5(not included) in array arr: 
arr[0:5]

array([1, 2, 3, 4, 5])

In [127]:
#print every other element from index 1 to index 7:
arr[1:7:2]

array([2, 4, 6])

In [128]:
#Return every other element from index1 to index7:
arr[0:10:2]

array([1, 3, 5, 7, 9])

In [129]:
#print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
# From the third element, slice elements from index 1 to index 5(not included) from array 'a' 
a[2,1:]

array([8, 9])

In [131]:
#In array 'a' print index 2 from all the rows:
arr[2]

3

In [132]:
#from all the elements in 'a', slice index 1 till end, this willl return a 2-Darray:
a[0:1:]

array([[1, 2, 3]])

## Numpy copy vs view


In [133]:
x1 = np.arange(10)


In [134]:
# assign x2 = x1
x2 = x1

In [135]:
# print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Ok now you have seen that both of them are same


In [136]:
#change 1st element of x2 as 10
x2[0] = 10

In [137]:
# Again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


Wait a minute. Just check your above result on change of X2, X1 also got changed.


Lets check if both the variables shares memory.Use numpy **shares_memory()** function

In [138]:
#check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
1693565806672
1693565806672


Hey it's True they both share memory


Shall we try **view()** fucntion also likewise

In [139]:
# create a view of x1 and store it in x3
x3 = x1.view()

In [140]:
# Again check memory share between x1 and x3
print(np.shares_memory(x1, x3))

True


In [141]:
#chnage 1st element of x3=100
x3[0] = 100

In [142]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


Now its proved

Lets see how **copy()** fucntion works

In [143]:
#Now create an array x4 whcih is copy of x1
x4 = np.copy(x1)

In [144]:
#change the last element of x4 as 900
x4[-1] = 900

In [145]:
#print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


Hey! such an intresting output.You noticed buddy =! your original array didn't get changed on 

In [146]:
#Check memory share between x1 and x4
np.shares_memory(x1, x4)

False

You see x1 and x4 dont share its memory.

So with all our outputs we can takeaway few points:

1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view  of the original array

2. The copy own the data any changes made to the copy will not affect original array,and any changes made to the original array will not affect the copy

3. The view does not own the data and any chnages made to the view will affect the orginal array, and any changes made to the original array will affect the view.

# More operations on Numpy

### 1. Applying conditions

In [147]:
#print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We are going to use 'a' array for all our array condition operations.

In [148]:
#check if every element in array a greater than 3 or not using '>' notation
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [149]:
#Get a list with all elements of array 'a' greater than 3
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [150]:
#Get a list with all elements of array 'a' greater than 3 and less than 6
a[(a>3) & (a<6)]

array([4, 5])

In [151]:
#check if each elements in array 'x1' equals array 'x' using '==' notation
x1 == x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

You can see in above output that the last element is not same in both x1 and x4

### 2. Transposing array

In [152]:
#print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("----------------------")
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
----------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In above output all the rows became columns by transposing

### 3. hstack vs vsatck function:

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides helper function:
1. hstack() to stack along rows
2. vstack() to stack along columns

<img src="hstack.png">

In [153]:
#stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [154]:
#stack  x1 and x4 along rows
np.hstack((x1, x4))

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

# Adding, Insert and delete Numpy array

Let use **insert()** function which inserts values into array before specified index value

In [156]:
#Insert values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [157]:
#delete 2nd element from array x2
print(x2)
np.delete(x2, 1)

[100   1   2   3   4   5   6   7   8   9]


array([100,   2,   3,   4,   5,   6,   7,   8,   9])

Did you see? 2 value is deleted from x2 whcih was at index position 2

# Mathematical opertions on Numpy array

In [158]:
#defining a
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [159]:
# print trigonometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [160]:
# print trigonometric cos value of each element of a
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [161]:
# print trigonometric exp value of each element of a
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [162]:
# print total sum of elements of a
np.sum(a)

45

In [163]:
#print sum in array a column wise
np.sum(a, axis=1)

array([ 6, 15, 24])

In [164]:
#print sum in array a row wise
np.sum(a, axis=0)

array([12, 15, 18])

<img src="mean.png">

In [165]:
#print median of array a
np.median(a)

5.0

In [166]:
#print mean of array a
np.mean(a)

5.0

<img src="SD.png">

In [167]:
#print standard deviation of array a
np.std(a)

2.581988897471611

In [168]:
#print largest element of array a
np.max(a)

9

In [169]:
#print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

# Searching Arrays

You can search an array for a certain value,and return the indexes that get a match

To search an array, use the **where()** method

In [170]:
#print the indexes where the value is 4 in array x1

m = np.where(x1 == 4)
print(m)

(array([4], dtype=int64),)


In [171]:
# print array x1
x1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [172]:
# print the indexes where the value is 4 in array x
np.where(x1%2 == 0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [173]:
# print x1 where x1 than 5, also if number is less than 5 then replace it with 0
np.where (x1>5, x1, 0)

array([100,   0,   0,   0,   0,   0,   6,   7,   8,   9])